# Generated by Django 3.0.5 on 2020-04-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
            ],
        ),
    ]
